apiVersion: v1
appVersion: [[ .AppVersion ]]
name: starboard-exporter
description: A Helm chart for starboard-exporter
engine: gotpl
home: https://github.com/giantswarm/starboard-exporter
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: "security"
  config.giantswarm.io/version: "master"
