apiVersion: v1
appVersion: 1.0.3
name: starboard-exporter
description: A Helm chart for starboard-exporter, which exposes Prometheus metrics from Aqua VulnerabilityReport and other custom resources.
engine: gotpl
home: https://github.com/giantswarm/starboard-exporter
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
version: 1.0.3
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "shield"
