apiVersion: v1
appVersion: 0.8.1
name: starboard-exporter
description: A Helm chart for starboard-exporter, which exposes Prometheus metrics from Aqua VulnerabilityReport and other custom resources.
engine: gotpl
home: https://github.com/giantswarm/starboard-exporter
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
version: 0.8.1
annotations:
  application.giantswarm.io/team: "shield"
  config.giantswarm.io/version: 1.x.x
